In [1]:
import numpy as np#numpy kütüphanesini kullanabilmek için ilk önce import eder. np numpy'in kısaltmasından gelir.

In [2]:
liste= list(range(1,10))#1 ve 10 aralığında sayılar oluşturur. 1'i dahil eder, 10'u dahil etmez.


In [3]:
liste#listeyi ekrana yazdırır.

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
a=np.array([1,2,3,4,5])#a isminde "1,2,3,4,5" elamanlarını içeren bir dizi oluşturur.


In [5]:
a#oluşturduğumuz a dizsini ekranda yazdırır.

array([1, 2, 3, 4, 5])

In [6]:
b=np.array(liste,dtype=float)#b dizisinin elemanlarını float(ondalıklı sayı) olarak yazdırır.
b#oluşturduğumuz b dizsini ekrana yazdırır.

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [7]:
c= np.arange(10,50,5)#arange metodu ile 10'dan 50'ye kadar 5'er 5'er artan bir dizi oluşturuyoruz. Bu diziye de c adını verir.
c#oluşturduğumuz c dizisini ekrana yazdırır. 

array([10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
d=np.linspace(0,1,10)#0 ve 1 arasında 1 dahil olmak üzere 10 tane sayı oluşturur.
d#oluşturduğumuz d'yi ekrana yazdırır.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
len(a)#a dizisinin boyutunu verir.
b.shape#b'nin boyutlarını verir.
b=b.reshape(3,3)#b nin boyutlarını 3'e 3lük olacak şekilde yeniden belirler. 
b#oluşturulan b matrisini ekrana yazdırır.
b.shape#b'nin boyutlarını verir.

(3, 3)

In [10]:
np.zeros((5,5))#elemanlarının hepsinin 0 olduğu 5*5'lik dizi oluşturur.
np.ones((5,5))#elemanlarının hepsinin 1 olduğu 5*5'lik bir dizi oluşturur.
np.eye(3)#3*3'lük bir birim matris oluşturur.
np.full((5,5),10)#5*5'lik bir matrisin elemanlarının hepsinin 10'dan oluşmasını sağlar.

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [11]:
a=np.random.random((2,2))#2'ye 2 boyutunda rastgele değerlerle dizi oluşturur.
b=np.random.randint(1,5,(2,2))#2'ye 2 boyutunda 1 ve 5 arasında rastgele değerlden dizi oluşturur.

In [12]:
a#a'yı ekrana yazdırır.

array([[0.83086689, 0.73606531],
       [0.11516217, 0.93558219]])

In [13]:
b#b'yi ekrana yazdırır.

array([[2, 4],
       [3, 3]])

In [14]:
np.add(a,b)#a ve b'yi toplar.

array([[2.83086689, 4.73606531],
       [3.11516217, 3.93558219]])

In [15]:
dir(np)#numpy'in metotlarını listeler.
help(np.multiply)#help komutuyla herhangi bir konu hakkında hızlıca bilgi alınabilir.Buradaki komutla da multiply  ilgili bilgi alınır.

Help on ufunc:

multiply = <ufunc 'multiply'>
    multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Multiply arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        Input arrays to be multiplied.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        El

In [16]:
np.median(c)#c dizisinin medyanını(ortadaki değerini) verir.
np.sum(c)#c dizisinin elemanlarının toplamını verir.
np.min(c)#c dizsinin en küçük değerini verir.
np.max(c)#c dizsinin en büyük değerini verir.

45

In [17]:
np.transpose(b)#b matrsinin transpozunu alır.
b.T#b matrisinin transpozunu alır.

array([[2, 3],
       [4, 3]])

In [18]:
np.sum(b)#b'nin elemanlarının toplar.
np.sum(b,axis=1)#b'nin satırlarını toplar.Sütunları toplamak için de axis=0 yapılır.

array([6, 6])

In [19]:
e=b.copy()#b dizisini e adlı diziye kopyalar. Dizide yapılan değişikliklerden kopyası etkilenmez.
f=b.view()#b dizsini f'ye kopyalar.Ve yapılan değişikliklerden etkilenir.

In [20]:
b[1,1]=100#b'nin satırdaki 1.indis ve sütundaki 1. indise denk gelen yerini 100 yapar.
f#f'yi ekrana yazdır.

array([[  2,   4],
       [  3, 100]])

In [21]:
np.save("b.npy", b)#b'yi "b.npy" isminde bulunulan dizine kaydeder.
w=np.load("b.npy")#"b.npy" adlı diziyi w'ya yükler.

In [22]:
b<5#b dizisinin elemanlarının 5'ten küçük olup olmadığının kontrolünü yapar.

array([[ True,  True],
       [ True, False]])

In [23]:
x=np.array([1,2,3,4,5,6,7,8,9])#x dizisini "1,2,3,4,5,6,7,8,9"elemanlarında oluşan bir dizi olarak tanımlar.
x[5::2]#x dizisinin 5.indisdeki değerini ve ondan 2 sonra gelen değeri döndürür.

array([6, 8])

In [61]:
y=np.random.random((10,10))#10'a 10'luk rastgele sayılardan oluşan bir dizi tanımlar.
y

array([[0.66993568, 0.83407059, 0.67323322, 0.65586424, 0.83578795,
        0.36151754, 0.22353415, 0.81944374, 0.79140215, 0.51185175],
       [0.91992485, 0.33414645, 0.31428318, 0.62508679, 0.66119383,
        0.33320096, 0.79165692, 0.94003803, 0.76469199, 0.50003786],
       [0.59208475, 0.61347744, 0.7340716 , 0.12552709, 0.40624371,
        0.71493473, 0.08504423, 0.39086545, 0.00862804, 0.07627576],
       [0.61082094, 0.43023901, 0.83625391, 0.71327718, 0.33492172,
        0.65331944, 0.40603879, 0.8551385 , 0.46652011, 0.15670575],
       [0.81428371, 0.28122265, 0.34069836, 0.56288394, 0.83117982,
        0.1085101 , 0.46039913, 0.08735478, 0.96917356, 0.0972046 ],
       [0.4736181 , 0.93185684, 0.37142001, 0.21345608, 0.69828139,
        0.43706288, 0.63153582, 0.43354455, 0.37610518, 0.60662781],
       [0.53831809, 0.02046554, 0.17116478, 0.70426144, 0.28283794,
        0.64427731, 0.5936544 , 0.91494413, 0.61323752, 0.79795486],
       [0.76281044, 0.701204  , 0.5830662

In [62]:
y[5:7, 4::2]

array([[0.69828139, 0.63153582, 0.37610518],
       [0.28283794, 0.5936544 , 0.61323752]])

In [57]:
np.concatenate((a,b), axis=1)#a ve b dizilerini satırlar boyunca birleştirir. Eğer axis=0 deseydik sütunlar boyunca birleştirme yapardı. Yani axis=0 alt aalta, axis=1 yan yana yazar.

array([[  0.83086689,   0.73606531,   2.        ,   4.        ],
       [  0.11516217,   0.93558219,   3.        , 100.        ]])

In [53]:
b.ravel().shape#b dizisinin elemanları ravel() ile tek dizinde yazılır.shape ile de bu dizinin boyutu öğrenilir.

(4,)

In [54]:
np.hstack((a,b))# a ve b'yi satırlar boyunca birleştirir.

array([[  0.83086689,   0.73606531,   2.        ,   4.        ],
       [  0.11516217,   0.93558219,   3.        , 100.        ]])

In [34]:
np.corrcoef(y)#y dizisinin köşegenlerini 1 yapar.

array([[ 1.        ,  0.18137096,  0.0603966 ,  0.40917549,  0.43864848,
         0.08159239,  0.36653471, -0.63982285, -0.31999224,  0.33574332],
       [ 0.18137096,  1.        , -0.18661736,  0.01376812,  0.2058543 ,
         0.78669789, -0.5024578 ,  0.20840157, -0.46446327,  0.23243083],
       [ 0.0603966 , -0.18661736,  1.        , -0.10330737, -0.65562966,
         0.01313488, -0.13922812,  0.15350256, -0.21358887, -0.25570295],
       [ 0.40917549,  0.01376812, -0.10330737,  1.        ,  0.34159226,
        -0.14421833,  0.27467842, -0.24074922, -0.4026454 , -0.08980141],
       [ 0.43864848,  0.2058543 , -0.65562966,  0.34159226,  1.        ,
         0.16252382,  0.32405869, -0.43064763,  0.19554922,  0.19247576],
       [ 0.08159239,  0.78669789,  0.01313488, -0.14421833,  0.16252382,
         1.        , -0.69529349,  0.51104938, -0.12519254, -0.29897042],
       [ 0.36653471, -0.5024578 , -0.13922812,  0.27467842,  0.32405869,
        -0.69529349,  1.        , -0.83744221