## SİMGE YILDIRIM " Uygulamalı Veri Bilimi Ve Analitiği  Dersi "

### 1. Bir listeden, numpy dizisinden ve dict'den bir dizi nasıl oluşturulur?

In [141]:
#listeden dizi oluşturma
liste_dizisi= [1,2,3,4,5]#sıralı ve elemanları değiştirilebilir dizilerdir.
liste_dizisi#ekrana yazdırır.
import array as arr#array import edilir.
a=arr.array('i',(liste_dizisi))#integer tipinde tanımlanan liste diziye dönüştürülür.
type(a)#a nın tipi döndürülür.

array.array

In [288]:
#numpy dizisi oluşturma
import numpy as np# numpy modülünü kullanabilmek için import edilir.
np_dizisi=np.array([1,2,3,4,5])#numpy dizisi oluşturma.
np_dizisi#ekrana yazdırır.

array([1, 2, 3, 4, 5])

In [58]:
#sözlükten dizi oluşturma
import numpy as np#numpy import edilir.
import array#array import edilir.
s = { 1, 2, 3, 4 }#sözlük oluşturulur
a = np.array(list(s)) #sözlük diziye dönüştürlür.
a#ekrana yazdırılır.

array([1, 2, 3, 4])

In [19]:
import pandas as pd#pandas kütükhanesi import edilir.
set1={"A": ["A1","A2","A3","A4"],"B":["B1","B2","B3","B4"]}#birinci veri seti oluşturulur.
set2={"A": ["A5","A6","A7","A8"],"B":["B5","B6","B7","B8"]}#ikinci veri seti oluşturulur.
df1 = pd.DataFrame(set1,index = [1,2,3,4])#verilerin indexleri belirtilir.
df2 = pd.DataFrame(set2,index = [5,6,7,8] )#verilerin indexleri belirtilir.
yeni = pd.concat([df1,df2]) #başlıklar veya indexler üzerinden direkt birleştirme işlemi yapar.
yeni#ekrana yazdırılır

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
5  A5  B5
6  A6  B6
7  A7  B7
8  A8  B8

### 2. Bir veri çerçevesi oluşturmak için birçok seri nasıl birleştirilir?


In [50]:
import pandas as pd#pandas import edilir.
a=['Simge', 'Hüsna','Ali', 'Seda','Mert', 'Cem']#a listesi oluşturulur.
students = pd.Series(a)#seriye dönüştürülür.
b=['C++', 'C#', 'RUBY', 'SWIFT','GO', 'PYTHON']#b listesi oluşturulur.
dersler = pd.Series(b)#seriye dönüştürülür.
c=[100, 30, 50, 70, 80, 60]#c listesi oluşturulur.
puanlar = pd.Series(c)#seriye dönüştürlür.
data = {"students": students, "dersler": subject,"puanlar": marks}#sözlük oluşturulur.
df = pd.concat(data,axis = 1)#serileri yan yana birleştirir.axis=0  alt alta birleştirir
df

students dersler  puanlar
0    Simge     C++      100
1    Hüsna      C#       30
2      Ali    RUBY       50
3     Seda   SWIFT       70
4     Mert      GO       80
5      Cem  PYTHON       60

 ### 3. B serisinde bulunmayan A serisinin öğeleri nasıl elde edilir?

In [73]:
import pandas as pd#pandas import edilir.
A = pd.Series([28, 45, 8, 22, 11, 47, 99])#A serisi oluşturulur.
B = pd.Series([14, 28, 47, 4, 11, 99, 12])#B serisi oluşturulur.
print("B serisinde bulunmayan A serisinin öğeleri:")
x = A[~A.isin(B)]#B serisinde bulunmayan A serisinin öğeleri x e atanır.
x#ekrana yazdırılır.

B serisinde bulunmayan A serisinin öğeleri:


0    28
4    11
5    47
6    99
dtype: int64

### 4. Hem A serisinde hem de B serisinde ortak olan öğeler nasıl elde edilir?

In [76]:
import pandas as pd#pandas import edilir.
A = pd.Series([28, 45, 8, 22, 11, 47, 99])#A serisi oluşturulur.
B = pd.Series([14, 28, 47, 4, 11, 99, 12])#B serisi oluşturulur.
print("hem A serisinde hem B serisinde ortak olan öğeler:")
x = A[A.isin(B)]#B serisinde ve A serisindeki ortak öğeleri x e atanır.
x#ekrana yazdırılır.

hem A serisinde hem B serisinde ortak olan öğeler:


0    28
4    11
5    47
6    99
dtype: int64

### 5. Yararlı bilgiler nasıl elde edilir?

In [5]:
import numpy as np#numpy import edilir.
import pandas as pd#pandas import edilir.
#dataframe oluşturma
dict = {'1.puan':[100, 90, np.nan, 95],'2.puan': [30, 45, 56, np.nan],'3.puan':[np.nan, 40, 80, 98]}# sözlük oluşturulur.1
df = pd.DataFrame(dict)# dataframe oluşturulur.
df.describe()#ekrana yararlı bilgileri yazar.(mean,std, vb)


1.puan     2.puan     3.puan
count     3.0   3.000000   3.000000
mean     95.0  43.666667  72.666667
std       5.0  13.051181  29.687259
min      90.0  30.000000  40.000000
25%      92.5  37.500000  60.000000
50%      95.0  45.000000  80.000000
75%      97.5  50.500000  89.000000
max     100.0  56.000000  98.000000

### 6. Bir serinin benzersiz öğelerinin sıklık sayıları nasıl alınır?

In [127]:
import pandas as pd#pandas import edilir.
s = pd.Series(data = [2, 3, 4, 5, 5, 6,7, 8, 9, 5, 3])# seri oluşturulur.
s.value_counts()# benzersiz sayıyı bulma

5    3
3    2
2    1
4    1
6    1
7    1
8    1
9    1
dtype: int64

### 7. Numpy dizisini verilen şekle sahip bir veri çerçevesine nasıl dönüştürebilirim? (L1)

In [139]:
import numpy as np#numpy import edilir.
import pandas as pd#pandas import edilir.
arr = np.array([[1, 2], [4, 5]])#numpy dizisi oluşturur.
arr#ekrana yazdırır.

array([[1, 2],
       [4, 5]])

In [140]:
df=pd.DataFrame(data= arr,index=["a","b"],columns=["c","d"])#diziyi istenen dataframe e çevirir.
df#ekrana yazdırır.

c  d
a  1  2
b  4  5

### 8. Bir diziden 3'ün katı olan sayıların konumları nasıl bulunur?

In [133]:
dizi = [18,15,22,19,85,9,32,65,7,55,3]#dizi oluşturulur
for sayi in dizi:#for döngüsü  dizideki her elemanı sayiya kopyalar
    if sayi%3 == 0:#sayi nın 3'e bölümünden kalanı sıfır olanları bulur
        print(dizi.index(sayi))#dizideki sayi nın 3'e bölümünden kalanı sıfır olanları yazdırır.

0
1
5
10


### 9. Bir diziden belirli konumlardaki öğeler nasıl çıkarılır?

In [142]:
C=[1,2,4,8,79,6,3,12]#C dizisi oluşturulur.
C.pop(2)# dizinin 4. indisteki elemanını çıkarır.
C#dizi ekrana yazdırılır.

[1, 2, 8, 79, 6, 3, 12]

### 10. İki dizi dikey ve yatay olarak nasıl istiflenir?

In [134]:
import numpy as np#numpy import edilir.
d1 = np.array([ 1, 2, 3] )#1.dizi oluşturulur.
d2 = np.array([ 4, 5, 6] )#2.dizi oluşturulur.
yatay = np.hstack((d1, d2))#iki dizi yatay olarak istiflenir.h horizontally den gelir.
yatay#ekrana yazdırılır.

array([1, 2, 3, 4, 5, 6])

In [138]:
import numpy as np#numpy import edilir.
d1 = np.array([ 1, 2, 3] )#1.dizi oluşturulur.
d2 = np.array([ 4, 5, 6] )#2.dizi oluşturulur.
dikey=np.vstack((d1,d2))#iki dizi dikey olarak istiflenir.v vertically den gelir.
dikey#ekrana yazdırılır.

array([[1, 2, 3],
       [4, 5, 6]])

### 11. Başka bir B serisindeki A serisi öğelerinin konumları nasıl alınır?

In [85]:
import pandas as pd#pandas import edilir.
A = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])#A serisi oluşturulur.
A#ekrana yazdırılır.

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [86]:
B = pd.Series([1, 3, 5, 7, 10])#B serisi oluşturulur.
B#ekrana yazdırılır.

0     1
1     3
2     5
3     7
4    10
dtype: int64

In [90]:
konum = [pd.Index(A).get_loc(i) for i in B]#B serisindeki A serisinin öğelerinin konumlarını atar konuma
konum#ekrana yazdırır

[0, 2, 4, 6, 9]

### 12. Bir serinin ardışık sayıları arasındaki farkların farkı nasıl hesaplanır?

In [129]:
import pandas as pd#pandas import edilir.
s1 = pd.Series([1, 3, 5, 8, 10, 11, 15])#seri oluşturulu.
print(s1.diff().tolist())#serinin ardışık sayıları arasındaki farkları ekrana yazdırır.

[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]


In [131]:
print(s1.diff().diff().tolist())#serinin ardışık sayıları arasındaki farkların farkını ekrana yazdırır.

[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


### 13. Bir dizi tarih dizisini bir zaman dizisine nasıl dönüştürebilirim?

In [124]:
import pandas as pd#pandas import edilir.
# bir dizi tarih dizisi oluşturulur
dt_series = pd.Series(['1997/05/28', '2013/01/16','2016/02/29 17:56'])# başlangıçta diziyi göster
dt_series
# sonra diziyi göster
# zaman serisine dönüştürüldü
print(pd.to_datetime(dt_series))


0   1997-05-28 00:00:00
1   2013-01-16 00:00:00
2   2016-02-29 17:56:00
dtype: datetime64[ns]


### 14. Bir diziden en az 2 sesli harf içeren kelimeler nasıl filtrelenir?

In [98]:
import pandas as pd#pandas imort edilir.
from collections import Counter#counter import edilir sayaç tutabilmek için
dizi= pd.Series(['Simge', 'Ali', 'Cem', 'Mert', 'Eda', 'Berk'])#seri oluşturulur.
sonuc = dizi.map(lambda c: sum([Counter(c.lower()).get(i, 0)# diziyi eşleme yapılır ve map ile dizilerde dolaşılır.
for i in list('aeiou')]) >= 2)#sesli harf sayısının >=2 olup olmadığını kontrol etme
dizi[sonuc]


0    Simge
1      Ali
4      Eda
dtype: object

### 15. En az kullanılan karakterle bir dizgede eksik boşluklar nasıl değiştirilir?

In [113]:
import pandas as pd#pandas import edilir.
n1 = 'simge yıldırım iyi günler'#içerisinde boşluk olan bir string alma
ser = pd.Series(list(n1))#karakter dizisine dönüştürme
frekans= ser.value_counts()#frekansı sayma
y = frekans.dropna().index[-1]#ilgili frekans ve karalterleri yazma
result = "".join(ser.replace(' ',y))#boşluklar kaldırılarak yeni karakterle değiştirilir
result#ekrana yazdırılır.

'simgenyıldırımniyingünler'

### 16. csv'yi bir veri çerçevesine aktarırken sütun değerleri nasıl değiştirilir?

In [31]:
import pandas as pd#pandas import edilir.
df = pd.read_csv("diabetes.csv")#csv dosyası okunur.
#veri/değer sütunlarının güncellenmesi
df.loc[3, 'BMI'] = 'Simge'# BMI sütunun 3.ndisindeki değei Simge yapar.
df.to_csv("yeni2.csv", index=False)#dosyanın içine yazar.
df#ekrana yazdırır.

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0              6      148             72             35        0   33.6   
1              1       85             66             29        0   26.6   
2              8      183             64              0        0   23.3   
3              1       89             66             23       94  Simge   
4              0      137             40             35      168   43.1   
..           ...      ...            ...            ...      ...    ...   
763           10      101             76             48      180   32.9   
764            2      122             70             27        0   36.8   
765            5      121             72             23      112   26.2   
766            1      126             60              0        0   30.1   
767            1       93             70             31        0   30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

### 17. Bir csv dosyasından yalnızca belirtilen sütunları nasıl içe aktarabilirim?

In [20]:
import pandas as pd#pandas import edilir.
#DataFrame oluşturulur.
data = pd.DataFrame({'x1':range(14, 22),'x2':[7, 3, 7, 5, 3, 9, 1, 8],'x3':['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],'x4':[9, 2, 1, 1, 4, 1, 4, 8]})
data.to_csv('data.csv')#csv ye aktarılır.
data1 = pd.read_csv('data.csv',usecols = ['x1', 'x4'])# CSV den dataframe okunur ve sütunlar belirtilir.
data1#içe aktarılanlar ekrana yazdırılır.

x1  x4
0  14   9
1  15   2
2  16   1
3  17   1
4  18   4
5  19   1
6  20   4
7  21   8

### 18. Bir veri çerçevesinin eksik değerleri olup olmadığı nasıl kontrol edilir?

In [292]:
import pandas as pd# pandas import edilir.
import numpy as np # numpy ,mport edilir.
dict = {'1.puan':[100, 90, np.nan, 95],'2.puan': [30, 45, 56, np.nan],'3.puan':[np.nan, 40, 80, 98]}# sözlük oluşturulur.1
df = pd.DataFrame(dict)# dataframe oluşturulur.
df.isnull()# isnull() fonksiyonu ile nan değerler true olarak döner.

1.puan  2.puan  3.puan
0   False   False    True
1   False   False   False
2    True   False   False
3   False    True   False

### 19. Birden çok sayısal sütunun eksik değerleri ortalama ile nasıl değiştirilir?

In [306]:
import numpy as np#numpy import edilir.
import pandas as pd#pandas import edilir.
#dataframe oluşturma
dict = {'1.puan':[100, 90, np.nan, 95],'2.puan': [30, 45, 56, np.nan],'3.puan':[np.nan, 40, 80, 98]}# sözlük oluşturulur.1
df = pd.DataFrame(dict)# dataframe oluşturulur.
df#ekrana yazdırılır.

1.puan  2.puan  3.puan
0   100.0    30.0     NaN
1    90.0    45.0    40.0
2     NaN    56.0    80.0
3    95.0     NaN    98.0

In [307]:
df.fillna(df.median())#fillna() işlevi ile eksik değerler ortalamayla değiştirilir.

1.puan  2.puan  3.puan
0   100.0    30.0    80.0
1    90.0    45.0    40.0
2    95.0    56.0    80.0
3    95.0    45.0    98.0

### 20. Bir veri çerçevesinin sütunlarının sırası nasıl değiştirilir?

In [295]:
import numpy as np#numpy import edilir.
import pandas as pd#pandas import edilir.
#dataframe oluşturma
df = pd.DataFrame({"A": np.random.randint(10, size=5),"B": np.random.randint(20, size=5),"C": np.random.randint(5, size=5),"D": np.random.randint(30, size=5)})
df.iloc[:, [2,3,1,0]]#dataframe in sütunlarının sıralarının değiştirilmesi

C   D   B  A
0  2  19   5  4
1  4  29   8  3
2  3  24  10  5
3  0  24   1  1
4  0  20  15  8

### 21. Bir veri çerçevesindeki her n. satır nasıl filtrelenir?

In [300]:
import numpy as np#numpy import edilir.
import pandas as pd#pandas import edilir.
#dataframe oluşturma
df = pd.DataFrame({"A": np.random.randint(10, size=5),"B": np.random.randint(20, size=5),"C": np.random.randint(5, size=5),"D": np.random.randint(30, size=5)})
df#datframe ekrana yazdırılır.

A   B  C   D
0  1   2  3   0
1  8  15  0  23
2  7  10  1  23
3  0   9  1   4
4  9  10  1  14

In [298]:
df.iloc[3]#datframe in 3.satırı filtrelenir.Hangi satır filtrelenmek isteniyorsa o değer girilir.

A     1
B    12
C     0
D    28
Name: 3, dtype: int32

### 22. Satır toplamı > 100 olan bir veri çerçevesinin son n satırı nasıl alınır?

In [308]:
import pandas as pd#pandas import edilir.
import numpy as np#numpy import edilir.
dict = {'ad': ['Simge', 'Ali', 'Funda','Ömer', 'Meltem'],'yas': [22, 20, np.inf, -np.inf, 22], 'puan': [90, 84, 33, 87, 82]}# dataframe için sözlük oluşturulur.
df = pd.DataFrame(dict)#sözlük dataframe e dönüştürülür
df#ekrana yazdırılır.

ad   yas  puan
0   Simge  22.0    90
1     Ali  20.0    84
2   Funda   inf    33
3    Ömer  -inf    87
4  Meltem  22.0    82

In [310]:
df.tail(2)#datframe in son 2 satırını verir.sondan kaç satırı döndürmek isterseniz onu girmelisiniz.

ad   yas  puan
3    Ömer  -inf    87
4  Meltem  22.0    82

In [313]:
import pandas as pd#pandas import edilir.
a=pd.read_csv('diabetes.csv')#csv dosyası okunur
a.tail(6)#csv dosyasının son n satırını döndürür.

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
762            9       89             62              0        0  22.5   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
762                     0.142   33        0  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

### 23. Bir dizi veya veri çerçevesi sütunundan aykırı değerler nasıl bulunur ve sınırlandırılır?

In [302]:
import numpy as np#numpy import edilir.
import pandas as pd#pandas import edilir.
#dataframe oluşturma
df = pd.DataFrame({"A": np.random.randint(10, size=5),"B": np.random.randint(20, size=5),"C": np.random.randint(5, size=5),"D": np.random.randint(30, size=5)})
df#datframe ekrana yazdırılır.


A   B  C   D
0  1  19  1   6
1  3  16  2  12
2  3   1  1  27
3  3   6  3   8
4  9   8  2  17

In [303]:
df[::-1]#dataframe in satırlarını tersine çevirir.


A   B  C   D
4  9   8  2  17
3  3   6  3   8
2  3   1  1  27
1  3  16  2  12
0  1  19  1   6

### 24. Bir veri çerçevesinin satırları nasıl tersine çevrilir?

In [35]:
import pandas as pd#pandas  import edilir.
 
#sözlük tanımlanır
data = {'gelir': [150000, 13000, 11000, 11000],'gider': [10000, 11000, 7000, 50000],'kar': [5000, 2000, 4000, 6000]}
dataframe = pd.DataFrame(data)#dataframe oluşturulur
dataframe#ekrana yazdırılur.

gelir  gider   kar
0  150000  10000  5000
1   13000  11000  2000
2   11000   7000  4000
3   11000  50000  6000

In [36]:
# iloc() Fonksiyonu ile satırlar tersine çevrilir.
ters = dataframe.iloc[::-1]
ters#ekrana yazdırılır.

gelir  gider   kar
3   11000  50000  6000
2   11000   7000  4000
1   13000  11000  2000
0  150000  10000  5000